import type { Scenario } from "./types";

/**
 * The scenario library. Each ticket is a short, branching conversation.
 * Exactly one (sometimes more) option per step is `correct` and advances the ticket.
 * Wrong picks cost CSAT and give coaching, but the player can try again.
 */
export const SCENARIOS: Scenario[] = [
  // ---------- DIFFICULTY 1 ----------
  {
    id: "pw-reset-basic",
    title: "Locked out after vacation",
    category: "Accounts",
    tier: "Standard",
    difficulty: 1,
    minLevel: 1,
    xp: 60,
    slaSeconds: 90,
    tags: ["password", "account", "verify"],
    summary: "A user is locked out of their account after two weeks off.",
    persona: {
      name: "Dana Kim",
      role: "Marketing Coordinator",
      company: "Northwind Retail",
      avatar: "🧑‍💼",
      pitch: 1.05,
      rate: 1,
      voiceHint: "female",
    },
    steps: [
      {
        clientMessage:
          "Hi! I just got back from vacation and my password won't work. I have a deadline in an hour, can you help?",
        clientMood: "confused",
        kb: ["kb-verify-identity", "kb-password-reset"],
        options: [
          {
            id: "verify",
            text: "\"Absolutely, I can help. First, can you confirm your full name and employee ID so I can verify the account?\"",
            correct: true,
            reply: "Sure — Dana Kim, employee ID 40192.",
            mood: "calm",
            csat: 6,
          },
          {
            id: "reset-now",
            text: "\"No problem, resetting it right now to Welcome123.\"",
            correct: false,
            reply: "Oh... don't you need to check it's me first?",
            mood: "confused",
            csat: -12,
            coaching: "Never reset credentials before verifying identity — it's the top social-engineering risk.",
          },
          {
            id: "brush-off",
            text: "\"Passwords expire every 90 days, that's just policy.\"",
            correct: false,
            reply: "Okay but... I still can't log in. Can you actually help?",
            mood: "annoyed",
            csat: -8,
            coaching: "Lead with help, not policy. Acknowledge the impact first.",
          },
        ],
      },
      {
        clientMessage: "Dana Kim, employee ID 40192. What's next?",
        clientMood: "calm",
        kb: ["kb-password-reset", "kb-mfa"],
        options: [
          {
            id: "temp",
            text: "Send a self-service reset link and set the account to force a password change at next login.",
            correct: true,
            reply: "Got the email — resetting now. It worked!",
            mood: "friendly",
            csat: 8,
          },
          {
            id: "read-aloud",
            text: "Read a permanent password out loud over the chat so she can log in.",
            correct: false,
            reply: "Should you really be typing my password in here?",
            mood: "annoyed",
            csat: -10,
            coaching: "Use self-service links or temp passwords forced to change — never share permanent secrets in chat.",
          },
        ],
      },
      {
        clientMessage: "I'm back in! Thank you so much.",
        clientMood: "friendly",
        options: [
          {
            id: "confirm-mfa",
            text: "Confirm her MFA still works, then close the ticket with a summary.",
            correct: true,
            reply: "MFA prompt came through fine. You're a lifesaver!",
            mood: "friendly",
            csat: 6,
          },
          {
            id: "close-fast",
            text: "Close the ticket immediately without checking anything else.",
            correct: false,
            reply: "Wait — will my phone login still work? I'm not sure.",
            mood: "confused",
            csat: -6,
            coaching: "Verify MFA and full access before closing, or you'll get a repeat ticket.",
          },
        ],
      },
    ],
  },
  {
    id: "printer-basic",
    title: "The printer that won't",
    category: "Hardware",
    tier: "Standard",
    difficulty: 1,
    minLevel: 1,
    xp: 55,
    slaSeconds: 120,
    tags: ["printer", "spooler"],
    summary: "Front-desk printer shows 'ready' but nothing prints.",
    persona: {
      name: "Marcus Bell",
      role: "Receptionist",
      company: "Northwind Retail",
      avatar: "🧑",
      pitch: 0.95,
      rate: 1,
      voiceHint: "male",
    },
    steps: [
      {
        clientMessage:
          "The lobby printer says 'ready' but nothing comes out. I've clicked print like ten times!",
        clientMood: "annoyed",
        kb: ["kb-printer"],
        options: [
          {
            id: "queue",
            text: "\"Let's check the print queue — sometimes jobs get stuck. Can you open it for me?\"",
            correct: true,
            reply: "Oh wow, there are eleven jobs stuck in there.",
            mood: "confused",
            csat: 6,
          },
          {
            id: "buy-new",
            text: "\"Sounds broken. I'll order a replacement printer.\"",
            correct: false,
            reply: "Really? It seemed fine yesterday...",
            mood: "confused",
            csat: -8,
            coaching: "Troubleshoot before replacing hardware. Stuck queues are the usual culprit.",
          },
        ],
      },
      {
        clientMessage: "Eleven stuck jobs. Should I just hit print again?",
        clientMood: "confused",
        kb: ["kb-printer"],
        options: [
          {
            id: "spooler",
            text: "Clear the queue and restart the Print Spooler service, then send one test page.",
            correct: true,
            reply: "It's printing! The test page just came out.",
            mood: "friendly",
            csat: 9,
          },
          {
            id: "more",
            text: "Tell him to keep clicking print until one goes through.",
            correct: false,
            reply: "Now there are fifteen stuck jobs and still nothing.",
            mood: "annoyed",
            csat: -9,
            coaching: "Adding jobs to a jammed queue makes it worse. Clear it and restart the spooler.",
          },
        ],
      },
    ],
  },

  // ---------- DIFFICULTY 2 ----------
  {
    id: "wifi-drop",
    title: "Wi-Fi keeps dropping",
    category: "Network",
    tier: "Priority",
    difficulty: 2,
    minLevel: 1,
    xp: 80,
    slaSeconds: 150,
    tags: ["network", "wifi", "triage"],
    summary: "One user's laptop drops Wi-Fi every few minutes.",
    persona: {
      name: "Priya Nair",
      role: "Financial Analyst",
      company: "Meridian Bank",
      avatar: "👩‍💻",
      pitch: 1.1,
      rate: 1.02,
      voiceHint: "female",
    },
    steps: [
      {
        clientMessage:
          "My Wi-Fi drops every couple minutes. It's driving me insane during video calls.",
        clientMood: "annoyed",
        kb: ["kb-network-triage"],
        options: [
          {
            id: "scope",
            text: "\"That's frustrating — let's fix it. Is anyone near you having the same issue, or just your laptop?\"",
            correct: true,
            reply: "Just me, I think. My deskmate is totally fine.",
            mood: "calm",
            csat: 6,
          },
          {
            id: "reboot-router",
            text: "Immediately reboot the whole floor's access point.",
            correct: false,
            reply: "Whoa, now EVERYONE around me got knocked offline!",
            mood: "panicked",
            csat: -14,
            coaching: "Scope the issue first. One user ≠ reboot shared infrastructure.",
          },
        ],
      },
      {
        clientMessage: "Just my laptop. What should I try?",
        clientMood: "calm",
        kb: ["kb-network-triage"],
        options: [
          {
            id: "forget",
            text: "Have her forget the network, update the Wi-Fi driver, and reconnect.",
            correct: true,
            reply: "Okay, updated the driver and reconnected... it's been stable for a few minutes now.",
            mood: "friendly",
            csat: 8,
          },
          {
            id: "airplane",
            text: "Tell her to just live with it and use ethernet forever.",
            correct: false,
            reply: "I move between meeting rooms all day, ethernet isn't realistic.",
            mood: "annoyed",
            csat: -8,
            coaching: "Offer a real fix, not a permanent workaround that ignores how they work.",
          },
        ],
      },
      {
        clientMessage: "Stable for five minutes — is that actually fixed?",
        clientMood: "calm",
        options: [
          {
            id: "monitor",
            text: "Log the driver fix, ask her to report back after her next call, and keep the ticket open 24h to confirm.",
            correct: true,
            reply: "That's reassuring. Calls are smooth now, thanks!",
            mood: "friendly",
            csat: 7,
          },
          {
            id: "close",
            text: "Close it instantly as resolved.",
            correct: false,
            reply: "It dropped again right after you closed it...",
            mood: "annoyed",
            csat: -7,
            coaching: "For intermittent issues, confirm stability over time before closing.",
          },
        ],
      },
    ],
  },
  {
    id: "email-sync",
    title: "Emails stopped arriving",
    category: "Email",
    tier: "Standard",
    difficulty: 2,
    minLevel: 1,
    xp: 75,
    slaSeconds: 150,
    tags: ["email", "outlook", "sync"],
    summary: "A user hasn't received email since this morning.",
    persona: {
      name: "Tomás Rivera",
      role: "Sales Rep",
      company: "Meridian Bank",
      avatar: "🧔",
      pitch: 0.9,
      rate: 0.98,
      voiceHint: "male",
    },
    steps: [
      {
        clientMessage:
          "I haven't gotten a single email since 9am. I've definitely missed client replies. Help!",
        clientMood: "panicked",
        kb: ["kb-email-sync", "kb-tone"],
        options: [
          {
            id: "acknowledge",
            text: "\"I understand how stressful that is with clients waiting — let's get this sorted fast. Can you still send email, or is it just receiving?\"",
            correct: true,
            reply: "Sending works... I just tested it. Receiving is dead.",
            mood: "confused",
            csat: 7,
          },
          {
            id: "blame",
            text: "\"You probably deleted them by accident.\"",
            correct: false,
            reply: "I did NOT delete anything. Wow.",
            mood: "annoyed",
            csat: -12,
            coaching: "Don't assign blame. Acknowledge impact, then diagnose.",
          },
        ],
      },
      {
        clientMessage: "Sending works, receiving is dead. What now?",
        clientMood: "confused",
        kb: ["kb-email-sync"],
        options: [
          {
            id: "check-rules",
            text: "Check for a runaway inbox rule and whether the mailbox is over quota.",
            correct: true,
            reply: "Found it — there's a rule dumping everything into a hidden folder. I never made that!",
            mood: "confused",
            csat: 8,
          },
          {
            id: "reinstall",
            text: "Wipe and reinstall his entire operating system.",
            correct: false,
            reply: "That feels like overkill for missing emails...?",
            mood: "annoyed",
            csat: -10,
            coaching: "Match the fix to the symptom. Reimaging for a mail rule is wildly disproportionate.",
          },
        ],
      },
      {
        clientMessage:
          "A rule I never made? That's creepy. Emails are flowing again now though.",
        clientMood: "confused",
        kb: ["kb-phishing"],
        options: [
          {
            id: "security",
            text: "Delete the rogue rule, reset his password as a precaution, and flag it to security as possible account compromise.",
            correct: true,
            reply: "Good call. Password reset done. I feel a lot safer now, thank you.",
            mood: "friendly",
            csat: 9,
          },
          {
            id: "ignore",
            text: "Just delete the rule and move on.",
            correct: false,
            reply: "But how did the rule get there in the first place?",
            mood: "confused",
            csat: -6,
            coaching: "An auto-forward/rule you didn't create is a classic sign of account compromise. Escalate.",
          },
        ],
      },
    ],
  },

  // ---------- DIFFICULTY 3 ----------
  {
    id: "vpn-exec",
    title: "Executive can't VPN before board call",
    category: "Network",
    tier: "Executive",
    difficulty: 3,
    minLevel: 2,
    xp: 130,
    slaSeconds: 120,
    tags: ["vpn", "executive", "pressure"],
    summary: "The CFO can't connect to VPN 10 minutes before a board meeting.",
    persona: {
      name: "Eleanor Voss",
      role: "Chief Financial Officer",
      company: "Meridian Bank",
      avatar: "👩‍⚖️",
      pitch: 1.0,
      rate: 1.05,
      voiceHint: "female",
    },
    steps: [
      {
        clientMessage:
          "This is Eleanor Voss. My VPN won't connect and I present to the board in ten minutes. Fix it. Now.",
        clientMood: "panicked",
        kb: ["kb-vpn", "kb-tone"],
        options: [
          {
            id: "calm-scope",
            text: "\"I've got you, Ms. Voss — we'll get you connected. Quick check: is your internet working otherwise, like a webpage loading?\"",
            correct: true,
            reply: "Yes, I'm reading email in the browser. Just the VPN app fails.",
            mood: "annoyed",
            csat: 8,
          },
          {
            id: "panic",
            text: "\"Uh, VPN issues can take a while, you might miss the meeting.\"",
            correct: false,
            reply: "That is NOT acceptable. Get me someone who can help.",
            mood: "panicked",
            csat: -16,
            coaching: "Under executive pressure, project calm competence. Never open with defeat.",
          },
        ],
      },
      {
        clientMessage: "Internet's fine, only the VPN app fails. It just spins.",
        clientMood: "annoyed",
        kb: ["kb-vpn"],
        options: [
          {
            id: "restart-client",
            text: "Have her fully quit the VPN client, confirm MFA approval on her phone, and reconnect to the nearest gateway.",
            correct: true,
            reply: "There was an MFA prompt I hadn't approved! Connected now.",
            mood: "calm",
            csat: 10,
          },
          {
            id: "reinstall-vpn",
            text: "Tell her to uninstall and reinstall the VPN client from scratch.",
            correct: false,
            reply: "I have NINE minutes. A reinstall is out of the question.",
            mood: "panicked",
            csat: -12,
            coaching: "Pick the fastest likely fix under time pressure. A missed MFA prompt is common and instant.",
          },
        ],
      },
      {
        clientMessage: "Connected! I can see the shared drive. Cutting it close.",
        clientMood: "calm",
        options: [
          {
            id: "standby",
            text: "Offer to stay on standby during her call and note the MFA tip for next time, then log the ticket.",
            correct: true,
            reply: "Very professional. I appreciate you. Consider this handled beautifully.",
            mood: "friendly",
            csat: 9,
          },
          {
            id: "bail",
            text: "\"Great, bye!\" and drop off immediately.",
            correct: false,
            reply: "...I suppose. A little abrupt.",
            mood: "annoyed",
            csat: -5,
            coaching: "With VIPs, offer standby support and a follow-up. Presence builds trust.",
          },
        ],
      },
    ],
  },
  {
    id: "slow-laptop",
    title: "Laptop 'basically unusable'",
    category: "Hardware",
    tier: "Priority",
    difficulty: 3,
    minLevel: 2,
    xp: 110,
    slaSeconds: 200,
    tags: ["performance", "hardware"],
    summary: "A developer's laptop has become painfully slow this week.",
    persona: {
      name: "Sam Okafor",
      role: "Software Developer",
      company: "Helix Labs",
      avatar: "🧑‍🔧",
      pitch: 0.92,
      rate: 1.0,
      voiceHint: "male",
    },
    steps: [
      {
        clientMessage:
          "My laptop is basically unusable this week. Builds take forever and it freezes constantly.",
        clientMood: "annoyed",
        kb: ["kb-slow-pc"],
        options: [
          {
            id: "when",
            text: "\"Let's dig in. When did it start, and have you rebooted recently? Also, how's your free disk space?\"",
            correct: true,
            reply: "Started Monday. Haven't rebooted in like 3 weeks. Disk is... 98% full, yikes.",
            mood: "confused",
            csat: 7,
          },
          {
            id: "new-laptop",
            text: "Immediately promise him a brand-new laptop.",
            correct: false,
            reply: "I mean I'd take it, but is my machine actually broken?",
            mood: "confused",
            csat: -6,
            coaching: "Diagnose before promising hardware. Full disks and long uptime cause exactly this.",
          },
        ],
      },
      {
        clientMessage:
          "Disk is 98% full and I haven't rebooted in weeks. That bad?",
        clientMood: "confused",
        kb: ["kb-slow-pc"],
        options: [
          {
            id: "cleanup",
            text: "Reboot, clear temp/build caches and old Docker images, and check Task Manager for a runaway process.",
            correct: true,
            reply: "Cleared 60GB of Docker junk and rebooted. Wow — it's snappy again!",
            mood: "friendly",
            csat: 10,
          },
          {
            id: "defrag-ssd",
            text: "Tell him to defragment his SSD daily.",
            correct: false,
            reply: "Pretty sure you shouldn't defrag SSDs? That'd just wear it out.",
            mood: "annoyed",
            csat: -10,
            coaching: "Don't defrag SSDs — it's pointless and adds wear. Free space and kill runaway processes.",
          },
        ],
      },
      {
        clientMessage: "Snappy again! But my disk will fill up again eventually.",
        clientMood: "friendly",
        options: [
          {
            id: "prevent",
            text: "Set up a disk-cleanup schedule, recommend a storage upgrade ticket, and document the cause.",
            correct: true,
            reply: "Love the proactive approach. Requesting the upgrade now. Thanks!",
            mood: "friendly",
            csat: 8,
          },
          {
            id: "shrug",
            text: "\"Just delete stuff when it gets slow again.\"",
            correct: false,
            reply: "So... I'll just be back here in a month?",
            mood: "annoyed",
            csat: -6,
            coaching: "Prevent repeat tickets with a proactive plan, not a reactive loop.",
          },
        ],
      },
    ],
  },
  {
    id: "software-license",
    title: "Design app 'trial expired'",
    category: "Software",
    tier: "Standard",
    difficulty: 3,
    minLevel: 2,
    xp: 100,
    slaSeconds: 200,
    tags: ["software", "license"],
    summary: "A designer's creative suite says the trial expired mid-project.",
    persona: {
      name: "Ivy Chen",
      role: "Graphic Designer",
      company: "Helix Labs",
      avatar: "👩‍🎨",
      pitch: 1.12,
      rate: 1.0,
      voiceHint: "female",
    },
    steps: [
      {
        clientMessage:
          "My design suite just said 'trial expired' and locked me out mid-project. I need this today!",
        clientMood: "panicked",
        kb: ["kb-software-install"],
        options: [
          {
            id: "check-license",
            text: "\"Let's get you unlocked. Are you signed in with your work account, or did the app install as a personal trial?\"",
            correct: true,
            reply: "Oh... I think I downloaded it myself and signed in with my personal email.",
            mood: "confused",
            csat: 7,
          },
          {
            id: "pirate",
            text: "Suggest she find a free 'cracked' version online to keep working.",
            correct: false,
            reply: "Isn't that... super against the rules?",
            mood: "confused",
            csat: -18,
            coaching: "Never suggest pirated software. It's a security and legal disaster. Use licensed deployment.",
          },
        ],
      },
      {
        clientMessage:
          "Yeah, personal email and a self-download. Is that a problem?",
        clientMood: "confused",
        kb: ["kb-software-install"],
        options: [
          {
            id: "portal",
            text: "Deploy the licensed version from the company software portal and sign her in with her work account.",
            correct: true,
            reply: "Installed from the portal, signed in with work email — full license active. My files opened!",
            mood: "friendly",
            csat: 9,
          },
          {
            id: "buy-personal",
            text: "Tell her to buy a personal subscription and expense it later.",
            correct: false,
            reply: "We already have licenses though, right? This seems wasteful.",
            mood: "annoyed",
            csat: -8,
            coaching: "Use existing company licenses via the portal rather than personal purchases.",
          },
        ],
      },
    ],
  },

  // ---------- DIFFICULTY 4 ----------
  {
    id: "phishing-report",
    title: "'I think I clicked something bad'",
    category: "Security",
    tier: "Priority",
    difficulty: 4,
    minLevel: 3,
    xp: 160,
    slaSeconds: 120,
    tags: ["phishing", "security", "incident"],
    summary: "A user entered their password on a fake login page.",
    persona: {
      name: "Grace Miller",
      role: "HR Specialist",
      company: "Helix Labs",
      avatar: "🧑‍💼",
      pitch: 1.08,
      rate: 1.05,
      voiceHint: "female",
    },
    steps: [
      {
        clientMessage:
          "I got an email that looked like IT... I clicked the link and typed my password before I realized. I'm so sorry!",
        clientMood: "panicked",
        kb: ["kb-phishing", "kb-tone"],
        options: [
          {
            id: "reassure-act",
            text: "\"Thank you for telling me right away — that's exactly the right move. Let's act fast. Did you enter your password AND approve any MFA prompt?\"",
            correct: true,
            reply: "I entered the password... an MFA prompt popped up but I did NOT approve it.",
            mood: "confused",
            csat: 9,
          },
          {
            id: "scold",
            text: "\"You really shouldn't click links like that. This is a big problem.\"",
            correct: false,
            reply: "I know, I feel terrible... maybe I shouldn't have said anything.",
            mood: "panicked",
            csat: -16,
            coaching: "Never shame a reporter — it discourages future reporting. Reassure, then act.",
          },
        ],
      },
      {
        clientMessage:
          "Password entered, MFA prompt NOT approved. What do we do?",
        clientMood: "confused",
        kb: ["kb-phishing"],
        options: [
          {
            id: "reset-revoke",
            text: "Immediately reset her password, revoke active sessions, and confirm the attacker never got MFA.",
            correct: true,
            reply: "Done — password changed, and you kicked out all the sessions. That was fast.",
            mood: "calm",
            csat: 10,
          },
          {
            id: "wait",
            text: "Tell her to 'keep an eye on it' and reset the password tomorrow.",
            correct: false,
            reply: "Tomorrow?? What if they get in tonight?",
            mood: "panicked",
            csat: -14,
            coaching: "Compromised credentials are an emergency. Reset and revoke sessions NOW.",
          },
        ],
      },
      {
        clientMessage: "Okay, sessions revoked. Am I in trouble?",
        clientMood: "calm",
        kb: ["kb-phishing"],
        options: [
          {
            id: "escalate-report",
            text: "Reassure her, report the phishing email to the security team with headers, and check if others received it.",
            correct: true,
            reply: "You're the best. Reporting it might save my whole team. Thank you.",
            mood: "friendly",
            csat: 9,
          },
          {
            id: "solo",
            text: "Handle it silently and don't tell the security team.",
            correct: false,
            reply: "Shouldn't someone else know, in case coworkers got it too?",
            mood: "confused",
            csat: -8,
            coaching: "Phishing is rarely targeted at one person. Report it so the campaign can be blocked org-wide.",
          },
        ],
      },
    ],
  },
  {
    id: "network-outage",
    title: "Half the floor is offline",
    category: "Network",
    tier: "Priority",
    difficulty: 4,
    minLevel: 3,
    xp: 170,
    slaSeconds: 240,
    tags: ["network", "outage", "triage"],
    summary: "Multiple users on the 4th floor lost network at once.",
    persona: {
      name: "Derek Cole",
      role: "Operations Manager",
      company: "Northwind Retail",
      avatar: "🧑‍🏭",
      pitch: 0.88,
      rate: 1.0,
      voiceHint: "male",
    },
    steps: [
      {
        clientMessage:
          "The whole east side of the 4th floor just lost internet. Like fifteen people. We're dead in the water here.",
        clientMood: "panicked",
        kb: ["kb-network-triage"],
        options: [
          {
            id: "scope-major",
            text: "\"Understood, treating this as a priority. Are the affected people all wired, all Wi-Fi, or mixed? And are phones down too?\"",
            correct: true,
            reply: "All wired desks on that side. Wi-Fi and phones actually still work.",
            mood: "annoyed",
            csat: 8,
          },
          {
            id: "one-by-one",
            text: "Start troubleshooting each person's laptop individually.",
            correct: false,
            reply: "There are FIFTEEN of us. You want to do this one laptop at a time?",
            mood: "panicked",
            csat: -14,
            coaching: "When many users fail together, suspect shared infrastructure — not 15 laptops.",
          },
        ],
      },
      {
        clientMessage:
          "Only the wired desks on the east side. Wi-Fi's fine. Weird, right?",
        clientMood: "annoyed",
        kb: ["kb-network-triage"],
        options: [
          {
            id: "switch",
            text: "Suspect the access switch for that section — check its status and confirm with the network team.",
            correct: true,
            reply: "You nailed it — the east-side switch shows a fault light. Network team is on it.",
            mood: "calm",
            csat: 10,
          },
          {
            id: "dns",
            text: "Assume it's a DNS problem and have everyone flush DNS.",
            correct: false,
            reply: "If it were DNS, wouldn't Wi-Fi be broken too? These are on the same DNS.",
            mood: "annoyed",
            csat: -9,
            coaching: "The clue is 'wired-only, one section' — that points to a switch, not DNS.",
          },
        ],
      },
      {
        clientMessage:
          "Switch fault confirmed. What do we do while the network team swaps it?",
        clientMood: "calm",
        kb: ["kb-tone"],
        options: [
          {
            id: "workaround",
            text: "Give a clear ETA, suggest affected staff use Wi-Fi temporarily, and post a status update.",
            correct: true,
            reply: "Perfect — moved everyone to Wi-Fi, told the team the ETA. You kept us sane. Thanks.",
            mood: "friendly",
            csat: 9,
          },
          {
            id: "silent-wait",
            text: "Tell them to just wait and give no ETA or workaround.",
            correct: false,
            reply: "Wait how long? People are asking me every two minutes.",
            mood: "annoyed",
            csat: -8,
            coaching: "During outages, communication + a workaround matter as much as the fix.",
          },
        ],
      },
    ],
  },
  {
    id: "mobile-lost",
    title: "Lost phone with company email",
    category: "Mobile",
    tier: "VIP",
    difficulty: 4,
    minLevel: 3,
    xp: 150,
    slaSeconds: 150,
    tags: ["mobile", "mdm", "security"],
    summary: "A VIP left their phone in a taxi — it has full email access.",
    persona: {
      name: "Julian Frost",
      role: "VP of Sales",
      company: "Meridian Bank",
      avatar: "🕴️",
      pitch: 0.95,
      rate: 1.05,
      voiceHint: "male",
    },
    steps: [
      {
        clientMessage:
          "I left my phone in a taxi. It has all my work email and files. I'm panicking — what do we do?!",
        clientMood: "panicked",
        kb: ["kb-mobile-mdm", "kb-tone"],
        options: [
          {
            id: "mdm-locate",
            text: "\"We can protect your data right now. It's enrolled in our device management, so let's locate it and lock it immediately.\"",
            correct: true,
            reply: "Oh thank god. Yes, please lock it. Can you see where it is?",
            mood: "confused",
            csat: 9,
          },
          {
            id: "call-it",
            text: "Suggest he just keep calling the phone until someone answers.",
            correct: false,
            reply: "And if a stranger answers and reads my email in the meantime?",
            mood: "panicked",
            csat: -12,
            coaching: "Protect corporate data first via MDM lock. Recovery is secondary to security.",
          },
        ],
      },
      {
        clientMessage: "It's locked now. But what if I never get it back?",
        clientMood: "confused",
        kb: ["kb-mobile-mdm"],
        options: [
          {
            id: "selective-wipe",
            text: "Explain you can do a selective wipe of corporate data if it isn't recovered soon, preserving his personal photos.",
            correct: true,
            reply: "That's a relief — my kids' photos are on there. Let's give it a few hours, then wipe work data if needed.",
            mood: "calm",
            csat: 10,
          },
          {
            id: "full-wipe",
            text: "Full-wipe the entire device instantly, including all his personal data.",
            correct: false,
            reply: "You erased my family photos without asking?! Those are irreplaceable!",
            mood: "annoyed",
            csat: -12,
            coaching: "Prefer selective (corporate-only) wipe. Full-wiping personal data without consent destroys trust.",
          },
        ],
      },
      {
        clientMessage: "Okay. What should I do on my end right now?",
        clientMood: "calm",
        kb: ["kb-password-reset"],
        options: [
          {
            id: "reset-creds",
            text: "Have him change his password from another device and re-verify MFA, then set a reminder to wipe if not found.",
            correct: true,
            reply: "Password changed, MFA re-set. I feel back in control. You handled that perfectly.",
            mood: "friendly",
            csat: 9,
          },
          {
            id: "nothing",
            text: "Tell him there's nothing else to do but wait.",
            correct: false,
            reply: "Shouldn't I at least change my password to be safe?",
            mood: "confused",
            csat: -6,
            coaching: "Rotate credentials whenever a device with access is lost.",
          },
        ],
      },
    ],
  },

  // ---------- DIFFICULTY 5 ----------
  {
    id: "ransomware",
    title: "🚨 Ransomware on a shared drive",
    category: "Security",
    tier: "Executive",
    difficulty: 5,
    minLevel: 4,
    xp: 240,
    slaSeconds: 120,
    tags: ["ransomware", "incident", "critical"],
    summary: "Files are turning into '.locked' and a ransom note appeared.",
    persona: {
      name: "Nadia Petrov",
      role: "Finance Director",
      company: "Meridian Bank",
      avatar: "😰",
      pitch: 1.05,
      rate: 1.1,
      voiceHint: "female",
    },
    steps: [
      {
        clientMessage:
          "My files are all turning into '.locked' and there's a note demanding Bitcoin! It's spreading to the shared drive!!",
        clientMood: "panicked",
        kb: ["kb-malware", "kb-tone"],
        options: [
          {
            id: "isolate",
            text: "\"This is serious and you did right to call. Immediately: unplug the network cable / turn off Wi-Fi on that computer to stop it spreading. Do that now.\"",
            correct: true,
            reply: "Okay — network cable unplugged, Wi-Fi off. The spreading seems to have stopped on the share.",
            mood: "panicked",
            csat: 10,
          },
          {
            id: "pay",
            text: "Advise her to just pay the Bitcoin to get files back quickly.",
            correct: false,
            reply: "Pay them?? Is that even something we're allowed to do?",
            mood: "panicked",
            csat: -20,
            coaching: "Never advise paying ransoms. First priority is ISOLATION to stop the spread.",
          },
          {
            id: "power-off",
            text: "Tell her to hold the power button and hard-shutdown the machine.",
            correct: false,
            reply: "It's off now... but wait, did that just destroy any evidence?",
            mood: "confused",
            csat: -10,
            coaching: "Isolate from the network first. Hard power-off can destroy forensic memory evidence.",
          },
        ],
      },
      {
        clientMessage: "Isolated. My heart is pounding. What now?",
        clientMood: "panicked",
        kb: ["kb-malware"],
        options: [
          {
            id: "escalate-sec",
            text: "Declare a security incident, escalate to the incident-response team immediately, and identify who else has access to that share.",
            correct: true,
            reply: "IR team is being paged. I gave them the list of everyone on that share. Good.",
            mood: "confused",
            csat: 10,
          },
          {
            id: "diy",
            text: "Try to remove the ransomware yourself with a free tool from a random website.",
            correct: false,
            reply: "Should the desk really be DIY-ing an active ransomware attack?",
            mood: "annoyed",
            csat: -14,
            coaching: "Active ransomware = major incident. Escalate to IR immediately; don't improvise.",
          },
        ],
      },
      {
        clientMessage:
          "IR is engaged. Everyone on that share is asking me if THEIR files are safe.",
        clientMood: "confused",
        kb: ["kb-network-triage", "kb-tone"],
        options: [
          {
            id: "contain-comms",
            text: "Have others disconnect from the affected share, confirm backups exist, and send a calm all-hands status with clear instructions.",
            correct: true,
            reply: "Everyone's off the share, backups confirmed from last night. You turned chaos into a plan. Thank you.",
            mood: "friendly",
            csat: 10,
          },
          {
            id: "hide",
            text: "Tell everyone it's 'probably fine' and to keep working off the share.",
            correct: false,
            reply: "But if it's still spreading, aren't we making it worse?",
            mood: "panicked",
            csat: -16,
            coaching: "Contain first: get everyone off the affected resource and verify backups before reassuring.",
          },
        ],
      },
    ],
  },
  {
    id: "onboarding-day",
    title: "New hire, nothing works, starts in 15",
    category: "Accounts",
    tier: "Priority",
    difficulty: 5,
    minLevel: 4,
    xp: 210,
    slaSeconds: 240,
    tags: ["onboarding", "accounts", "provisioning"],
    summary: "A new hire's accounts were never provisioned and they start now.",
    persona: {
      name: "Leo Martins",
      role: "New Analyst (Day 1)",
      company: "Helix Labs",
      avatar: "🧑‍🎓",
      pitch: 1.0,
      rate: 1.05,
      voiceHint: "male",
    },
    steps: [
      {
        clientMessage:
          "Hi, it's my first day and... nothing works. No email, no laptop login, HR said IT would set me up? Orientation starts in 15 minutes.",
        clientMood: "confused",
        kb: ["kb-verify-identity", "kb-tone"],
        options: [
          {
            id: "welcome-verify",
            text: "\"Welcome to the team, Leo! Let's get you set up fast. Can you confirm your full name and start date so I can find your onboarding record?\"",
            correct: true,
            reply: "Leo Martins, starting today. HR emailed me an offer but I don't see an IT account anywhere.",
            mood: "calm",
            csat: 8,
          },
          {
            id: "not-my-job",
            text: "\"Onboarding is HR's job, you'll have to talk to them.\"",
            correct: false,
            reply: "HR literally just told me to talk to IT. I'm getting bounced around on day one...",
            mood: "annoyed",
            csat: -14,
            coaching: "Don't ping-pong the user. Own the problem and coordinate with HR yourself.",
          },
        ],
      },
      {
        clientMessage:
          "Offer email exists, but no IT account. Can you still help before orientation?",
        clientMood: "calm",
        kb: ["kb-password-reset", "kb-software-install"],
        options: [
          {
            id: "provision",
            text: "Confirm his identity with HR, provision his account with a temp password + MFA enrollment, and prioritize email so he can join orientation.",
            correct: true,
            reply: "I'm logging in! Email's coming through and I got the orientation invite. Huge relief.",
            mood: "friendly",
            csat: 10,
          },
          {
            id: "guess-access",
            text: "Grant him admin access to everything to save time.",
            correct: false,
            reply: "Should a brand-new analyst really have full admin rights on day one?",
            mood: "confused",
            csat: -12,
            coaching: "Least privilege matters even under pressure. Provision role-appropriate access, not blanket admin.",
          },
        ],
      },
      {
        clientMessage:
          "Logged in and in orientation. My laptop's still not here though.",
        clientMood: "friendly",
        kb: ["kb-tone"],
        options: [
          {
            id: "loaner",
            text: "Set him up with a loaner laptop now, file a ticket for his permanent device, and give a clear pickup time.",
            correct: true,
            reply: "A loaner works perfectly for today. Best first-day save ever — thank you!",
            mood: "friendly",
            csat: 9,
          },
          {
            id: "wait-device",
            text: "Tell him to just use his phone until his laptop 'shows up eventually'.",
            correct: false,
            reply: "For all my training today? On a phone screen?",
            mood: "annoyed",
            csat: -8,
            coaching: "Provide a real interim solution (loaner) with a timeline, not a vague wait.",
          },
        ],
      },
    ],
  },
  {
    id: "angry-vip-repeat",
    title: "Furious VIP, third time calling",
    category: "Software",
    tier: "Executive",
    difficulty: 5,
    minLevel: 4,
    xp: 230,
    slaSeconds: 200,
    tags: ["deescalation", "vip", "repeat"],
    summary: "An executive's app keeps crashing and they've called three times.",
    persona: {
      name: "Regina Hale",
      role: "Chief Operating Officer",
      company: "Northwind Retail",
      avatar: "😠",
      pitch: 1.02,
      rate: 1.12,
      voiceHint: "female",
    },
    steps: [
      {
        clientMessage:
          "This is the THIRD time I'm calling about this crashing app. Nobody has fixed it. I am done being patient.",
        clientMood: "annoyed",
        kb: ["kb-tone"],
        options: [
          {
            id: "own-it",
            text: "\"I'm sorry you've had to call three times — that's genuinely on us, and I'm going to own this until it's fixed. Let me pull the history so you don't repeat yourself.\"",
            correct: true,
            reply: "...Fine. Thank you. Finally someone who gets it. Yes, please read the history.",
            mood: "calm",
            csat: 10,
          },
          {
            id: "defensive",
            text: "\"Well, I don't see notes from those other calls, so I can't help with that.\"",
            correct: false,
            reply: "So your own system is broken too? Unbelievable.",
            mood: "panicked",
            csat: -18,
            coaching: "Own the org's failure, don't deflect. Repeat callers need accountability first.",
          },
        ],
      },
      {
        clientMessage:
          "The app crashes every time I open a large report. Every single time.",
        clientMood: "calm",
        kb: ["kb-slow-pc", "kb-software-install"],
        options: [
          {
            id: "reproduce",
            text: "Reproduce it with her: check the app version, clear its cache, and update to the latest build known to fix large-file crashes.",
            correct: true,
            reply: "Updated and cleared the cache... I just opened the huge report and it DIDN'T crash. Incredible.",
            mood: "friendly",
            csat: 10,
          },
          {
            id: "blame-file",
            text: "Tell her the report file is 'probably too big' and she should make smaller reports.",
            correct: false,
            reply: "I'm the COO. I'm not going to shrink my reports to fit your software.",
            mood: "annoyed",
            csat: -12,
            coaching: "Fix the tool, don't push the workaround onto the user — especially an executive.",
          },
        ],
      },
      {
        clientMessage:
          "It works now. But how do I know it won't happen a fourth time?",
        clientMood: "friendly",
        kb: ["kb-tone"],
        options: [
          {
            id: "followup-plan",
            text: "Document the root cause, add her to the fix's rollout, personally follow up in 48h, and give her your direct ticket reference.",
            correct: true,
            reply: "That is exactly the accountability I wanted. You've completely turned this around. Thank you.",
            mood: "friendly",
            csat: 10,
          },
          {
            id: "hope",
            text: "\"It should be fine now, fingers crossed!\"",
            correct: false,
            reply: "'Fingers crossed' is how I ended up calling three times.",
            mood: "annoyed",
            csat: -10,
            coaching: "After a repeat issue, commit to a concrete follow-up — never leave it to chance.",
          },
        ],
      },
    ],
  },

  // ---------- EXPANSION PACK ----------
  {
    id: "monitor-dead",
    title: "Second monitor won't wake up",
    category: "Hardware",
    tier: "Standard",
    difficulty: 1,
    minLevel: 1,
    xp: 55,
    slaSeconds: 120,
    tags: ["monitor", "hardware", "display"],
    summary: "A user's external monitor shows 'No Signal'.",
    persona: {
      name: "Owen Blake",
      role: "Accountant",
      company: "Northwind Retail",
      avatar: "🧑‍💻",
      pitch: 0.96,
      rate: 0.98,
      voiceHint: "male",
    },
    steps: [
      {
        clientMessage:
          "My second monitor just says 'No Signal'. It worked yesterday! I need both screens for spreadsheets.",
        clientMood: "annoyed",
        options: [
          {
            id: "cable",
            text: "\"Let's check the basics — is the video cable snug at both ends, and is the monitor on the right input source?\"",
            correct: true,
            reply: "Oh... the HDMI cable was half out. Pushed it in — still no signal though.",
            mood: "confused",
            csat: 6,
          },
          {
            id: "replace",
            text: "\"The monitor's dead, I'll order you a new one.\"",
            correct: false,
            reply: "Before even checking the cable? Seems hasty.",
            mood: "annoyed",
            csat: -8,
            coaching: "Check cables and inputs before condemning hardware.",
          },
        ],
      },
      {
        clientMessage: "Cable's in, still nothing. Now what?",
        clientMood: "confused",
        options: [
          {
            id: "detect",
            text: "Have him press Win+P to extend displays and use 'Detect display', and try a different cable/port.",
            correct: true,
            reply: "Switched the port and hit Detect — boom, it's back! Two screens again.",
            mood: "friendly",
            csat: 9,
          },
          {
            id: "reboot-only",
            text: "Tell him rebooting 10 times usually fixes it.",
            correct: false,
            reply: "Rebooted twice, no change. There must be a real step here.",
            mood: "annoyed",
            csat: -7,
            coaching: "Use display detection and swap the port/cable — don't rely on blind reboots.",
          },
        ],
      },
    ],
  },
  {
    id: "2fa-new-phone",
    title: "New phone, can't get 2FA codes",
    category: "Accounts",
    tier: "Standard",
    difficulty: 2,
    minLevel: 1,
    xp: 80,
    slaSeconds: 150,
    tags: ["mfa", "2fa", "accounts"],
    summary: "A user upgraded phones and lost their authenticator codes.",
    persona: {
      name: "Hana Suzuki",
      role: "Recruiter",
      company: "Helix Labs",
      avatar: "👩",
      pitch: 1.1,
      rate: 1.0,
      voiceHint: "female",
    },
    steps: [
      {
        clientMessage:
          "I got a new phone and now my authenticator app is empty — I can't log in anywhere. Help!",
        clientMood: "confused",
        kb: ["kb-mfa", "kb-verify-identity"],
        options: [
          {
            id: "verify",
            text: "\"No worries, this is common. First let me verify it's really you — can you confirm your employee ID and answer a verification question?\"",
            correct: true,
            reply: "Of course — ID 88231, and my manager is Priya Nair.",
            mood: "calm",
            csat: 7,
          },
          {
            id: "just-disable",
            text: "Disable MFA on her account so she can log in without it.",
            correct: false,
            reply: "Isn't turning off 2FA a security risk?",
            mood: "confused",
            csat: -12,
            coaching: "Never permanently disable MFA. Verify identity, then re-enroll the new device.",
          },
        ],
      },
      {
        clientMessage: "Verified! How do I get my codes back on the new phone?",
        clientMood: "calm",
        kb: ["kb-mfa"],
        options: [
          {
            id: "reenroll",
            text: "Remove the old authenticator factor, issue temporary bypass codes, and walk her through re-enrolling the app.",
            correct: true,
            reply: "Bypass code worked, re-enrolled the app, codes are flowing. Thank you!",
            mood: "friendly",
            csat: 9,
          },
          {
            id: "sms-forever",
            text: "Switch her to SMS codes permanently since it's easier.",
            correct: false,
            reply: "I heard SMS 2FA is the least secure option though?",
            mood: "confused",
            csat: -6,
            coaching: "Prefer an authenticator app over SMS. Re-enroll rather than downgrading security.",
          },
        ],
      },
    ],
  },
  {
    id: "meeting-no-audio",
    title: "No mic in a meeting starting now",
    category: "Software",
    tier: "Priority",
    difficulty: 2,
    minLevel: 1,
    xp: 80,
    slaSeconds: 120,
    tags: ["audio", "meetings", "software"],
    summary: "A user's microphone isn't working as their meeting starts.",
    persona: {
      name: "Carlos Mendez",
      role: "Account Executive",
      company: "Meridian Bank",
      avatar: "🧔",
      pitch: 0.9,
      rate: 1.05,
      voiceHint: "male",
    },
    steps: [
      {
        clientMessage:
          "Nobody can hear me in my video call and it's a client pitch! My mic just doesn't work!",
        clientMood: "panicked",
        options: [
          {
            id: "device",
            text: "\"Stay calm, we'll fix it live. In the meeting's audio settings, is the correct microphone selected — not 'Default' or a disconnected headset?\"",
            correct: true,
            reply: "It was set to my unplugged headset! Switched to laptop mic.",
            mood: "confused",
            csat: 8,
          },
          {
            id: "restart-pc",
            text: "Tell him to restart his whole computer right now.",
            correct: false,
            reply: "I can't reboot — I'm live with a client!",
            mood: "panicked",
            csat: -12,
            coaching: "During a live call, check the app's input device first. Rebooting drops the call.",
          },
        ],
      },
      {
        clientMessage: "Switched the mic — can they hear me now? Let me ask... yes!",
        clientMood: "friendly",
        options: [
          {
            id: "perms",
            text: "Confirm mic permissions are granted to the app and note the fix so it doesn't recur.",
            correct: true,
            reply: "Permissions look good. Crisis averted — you saved the pitch!",
            mood: "friendly",
            csat: 8,
          },
          {
            id: "bye",
            text: "Drop off without confirming it's stable.",
            correct: false,
            reply: "Wait, will it switch back to the headset next time?",
            mood: "confused",
            csat: -5,
            coaching: "Confirm the fix holds and set correct defaults to prevent a repeat.",
          },
        ],
      },
    ],
  },
  {
    id: "saas-outage",
    title: "Whole team locked out of the CRM",
    category: "Software",
    tier: "Priority",
    difficulty: 3,
    minLevel: 2,
    xp: 120,
    slaSeconds: 200,
    tags: ["saas", "outage", "vendor"],
    summary: "An entire team reports the CRM throwing errors.",
    persona: {
      name: "Rachel Green",
      role: "Sales Team Lead",
      company: "Meridian Bank",
      avatar: "👩‍💼",
      pitch: 1.08,
      rate: 1.02,
      voiceHint: "female",
    },
    steps: [
      {
        clientMessage:
          "My entire team of 12 is getting errors in the CRM — nobody can log calls. Is it just us?",
        clientMood: "annoyed",
        kb: ["kb-network-triage"],
        options: [
          {
            id: "check-status",
            text: "\"Let me check right now — I'll look at the CRM's status page and whether it's org-wide or just your team.\"",
            correct: true,
            reply: "Okay. My whole team is down at least. Others might be too.",
            mood: "calm",
            csat: 7,
          },
          {
            id: "reinstall-all",
            text: "Tell all 12 people to reinstall the CRM app individually.",
            correct: false,
            reply: "Reinstall on 12 machines for what might be a vendor outage?",
            mood: "annoyed",
            csat: -12,
            coaching: "When many users fail at once on a SaaS tool, check the vendor status page first.",
          },
        ],
      },
      {
        clientMessage: "So is it down for everyone or just us?",
        clientMood: "calm",
        options: [
          {
            id: "vendor",
            text: "The vendor status page confirms a provider-side outage — open a vendor ticket and broadcast an advisory with a workaround.",
            correct: true,
            reply: "Knowing it's the vendor (not us) helps a ton. We'll log calls in a sheet meanwhile. Thanks!",
            mood: "friendly",
            csat: 10,
          },
          {
            id: "blame-user",
            text: "Insist it must be their internet and to reset their routers.",
            correct: false,
            reply: "Everything else works fine — only the CRM is down. It's not our internet.",
            mood: "annoyed",
            csat: -10,
            coaching: "Don't force a wrong root cause. A confirmed vendor outage needs comms + a workaround.",
          },
        ],
      },
    ],
  },
  {
    id: "calendar-invites",
    title: "Meeting invites vanish",
    category: "Email",
    tier: "Standard",
    difficulty: 3,
    minLevel: 2,
    xp: 100,
    slaSeconds: 200,
    tags: ["calendar", "email", "delegation"],
    summary: "An exec assistant's calendar invites aren't reaching attendees.",
    persona: {
      name: "Bianca Rossi",
      role: "Executive Assistant",
      company: "Northwind Retail",
      avatar: "🧑‍💼",
      pitch: 1.12,
      rate: 1.04,
      voiceHint: "female",
    },
    steps: [
      {
        clientMessage:
          "I schedule meetings for three execs and lately attendees say they never got my invites. It's embarrassing!",
        clientMood: "annoyed",
        kb: ["kb-email-sync"],
        options: [
          {
            id: "delegation",
            text: "\"Let's dig in. Are you sending from your own calendar or as a delegate on the execs' calendars?\"",
            correct: true,
            reply: "As a delegate on all three. That started around when this began, actually.",
            mood: "confused",
            csat: 7,
          },
          {
            id: "resend",
            text: "Just tell her to resend everything and hope it works.",
            correct: false,
            reply: "I've resent them twice — same problem. There's clearly something deeper.",
            mood: "annoyed",
            csat: -7,
            coaching: "Find the root cause. Repeated resends without diagnosis waste everyone's time.",
          },
        ],
      },
      {
        clientMessage: "It's all delegate access. Is that the issue?",
        clientMood: "confused",
        kb: ["kb-email-sync"],
        options: [
          {
            id: "fix-perms",
            text: "Check delegate permissions and a blocking mail rule; correct the delegate 'send on behalf' settings.",
            correct: true,
            reply: "You found a rule quarantining outbound invites! Fixed — a test invite just landed. Amazing.",
            mood: "friendly",
            csat: 10,
          },
          {
            id: "new-account",
            text: "Create her a brand-new email account to start fresh.",
            correct: false,
            reply: "A whole new account won't fix delegate access to the execs though?",
            mood: "confused",
            csat: -8,
            coaching: "Target the actual cause (delegate perms / rules), not a disruptive account rebuild.",
          },
        ],
      },
    ],
  },
  {
    id: "docking-station",
    title: "Docking station mayhem",
    category: "Hardware",
    tier: "Standard",
    difficulty: 3,
    minLevel: 2,
    xp: 105,
    slaSeconds: 220,
    tags: ["dock", "peripherals", "hardware"],
    summary: "After a desk move, nothing on the dock works.",
    persona: {
      name: "Theo Park",
      role: "Data Analyst",
      company: "Helix Labs",
      avatar: "🧑‍🔬",
      pitch: 0.94,
      rate: 1.0,
      voiceHint: "male",
    },
    steps: [
      {
        clientMessage:
          "I moved desks and now my dock is useless — no monitors, keyboard, or ethernet. Everything's plugged in!",
        clientMood: "annoyed",
        options: [
          {
            id: "power-order",
            text: "\"Let's reseat it methodically. Is the dock's own power adapter connected, and is the single cable to the laptop fully seated?\"",
            correct: true,
            reply: "The dock power brick wasn't plugged into the wall! Lights came on now.",
            mood: "confused",
            csat: 7,
          },
          {
            id: "new-dock",
            text: "Assume the dock broke in the move and issue a replacement.",
            correct: false,
            reply: "It was working an hour ago before I unplugged it...",
            mood: "confused",
            csat: -7,
            coaching: "After a move, suspect power and reseated cables before replacing hardware.",
          },
        ],
      },
      {
        clientMessage: "Dock's powered now but monitors still black. Ideas?",
        clientMood: "confused",
        options: [
          {
            id: "firmware-detect",
            text: "Reseat the laptop cable, update the dock firmware/driver, and use display-detect for the monitors.",
            correct: true,
            reply: "Firmware update + detect did it — both monitors, keyboard, ethernet all back. Perfect.",
            mood: "friendly",
            csat: 9,
          },
          {
            id: "give-up",
            text: "Tell him to just use the laptop screen from now on.",
            correct: false,
            reply: "I analyze data all day — one small screen isn't workable.",
            mood: "annoyed",
            csat: -8,
            coaching: "Solve the dock (firmware + detect); don't push a workaround that hurts productivity.",
          },
        ],
      },
    ],
  },
  {
    id: "social-engineering",
    title: "🚩 Caller demands a password reset",
    category: "Security",
    tier: "Priority",
    difficulty: 4,
    minLevel: 3,
    xp: 175,
    slaSeconds: 180,
    tags: ["social-engineering", "security", "verify"],
    summary: "An aggressive caller claims to be an exec and wants instant access.",
    persona: {
      name: "'David from Finance'",
      role: "Unverified caller",
      company: "Unknown",
      avatar: "🕵️",
      pitch: 0.85,
      rate: 1.08,
      voiceHint: "male",
    },
    steps: [
      {
        clientMessage:
          "This is David, a VP in Finance. I'm traveling and locked out. Reset my password and read it to me NOW — I don't have time for questions.",
        clientMood: "annoyed",
        kb: ["kb-verify-identity"],
        options: [
          {
            id: "verify-anyway",
            text: "\"I understand you're in a hurry. For your account's protection I still have to verify identity — can you complete an MFA prompt or confirm details on file?\"",
            correct: true,
            reply: "This is ridiculous! I'm a VP! ...Fine, but hurry.",
            mood: "annoyed",
            csat: 8,
          },
          {
            id: "comply",
            text: "He sounds important and angry — reset it and read the password aloud.",
            correct: false,
            reply: "[The 'VP' hangs up. Later: an account is compromised.]",
            mood: "calm",
            csat: -22,
            coaching: "Urgency + authority + 'skip verification' is the classic social-engineering combo. Never bypass identity checks.",
          },
        ],
      },
      {
        clientMessage: "I don't have my work phone for MFA. Just trust me, I'll get you fired.",
        clientMood: "annoyed",
        kb: ["kb-verify-identity"],
        options: [
          {
            id: "hold-line",
            text: "Politely hold firm: offer a callback to the number on file or manager verification, and log the attempt for security.",
            correct: true,
            reply: "[Caller refuses a callback and disconnects.] Security later confirms: it was an impostor.",
            mood: "calm",
            csat: 10,
          },
          {
            id: "cave",
            text: "Cave to the threat and reset it to avoid getting in trouble.",
            correct: false,
            reply: "[Access granted to an attacker. This becomes a breach.]",
            mood: "calm",
            csat: -20,
            coaching: "Threats are a red flag, not a reason to skip policy. A real VP can verify via callback/manager.",
          },
        ],
      },
    ],
  },
  {
    id: "shared-mailbox",
    title: "Access to a shared mailbox",
    category: "Accounts",
    tier: "Standard",
    difficulty: 3,
    minLevel: 2,
    xp: 95,
    slaSeconds: 220,
    tags: ["permissions", "mailbox", "approval"],
    summary: "A user requests access to the 'billing@' shared mailbox.",
    persona: {
      name: "Nina Alvarez",
      role: "Billing Clerk",
      company: "Northwind Retail",
      avatar: "👩‍💼",
      pitch: 1.06,
      rate: 1.0,
      voiceHint: "female",
    },
    steps: [
      {
        clientMessage:
          "I need access to the billing@ shared mailbox — I just joined the billing team and can't see it.",
        clientMood: "calm",
        kb: ["kb-verify-identity"],
        options: [
          {
            id: "approval",
            text: "\"Happy to help. Access to shared mailboxes needs manager approval — can you confirm your manager so I can verify the request?\"",
            correct: true,
            reply: "Sure, my manager is the Billing Supervisor, Derek Cole.",
            mood: "calm",
            csat: 7,
          },
          {
            id: "grant-now",
            text: "Grant full access immediately — she seems legit.",
            correct: false,
            reply: "That was fast... don't you usually need sign-off for billing data?",
            mood: "confused",
            csat: -10,
            coaching: "Sensitive shared resources need proper authorization, even for friendly requests.",
          },
        ],
      },
      {
        clientMessage: "Derek approved it in chat just now. Can you set me up?",
        clientMood: "friendly",
        options: [
          {
            id: "least-priv",
            text: "Verify the approval, grant the appropriate role (not owner), and document who approved and when.",
            correct: true,
            reply: "I can see billing@ now with the right access. Clean and by-the-book — thank you!",
            mood: "friendly",
            csat: 9,
          },
          {
            id: "owner",
            text: "Make her the mailbox owner with full admin rights to be safe.",
            correct: false,
            reply: "Owner rights? I just need to read and reply, not run it.",
            mood: "confused",
            csat: -7,
            coaching: "Apply least privilege — grant the minimum role needed, not full ownership.",
          },
        ],
      },
    ],
  },
  {
    id: "offboarding",
    title: "🚨 Terminate access — employee let go NOW",
    category: "Security",
    tier: "Executive",
    difficulty: 5,
    minLevel: 4,
    xp: 220,
    slaSeconds: 150,
    tags: ["offboarding", "security", "access"],
    summary: "HR needs an employee's access cut immediately during a termination.",
    persona: {
      name: "Monica Shaw",
      role: "HR Director",
      company: "Helix Labs",
      avatar: "👩‍⚖️",
      pitch: 1.04,
      rate: 1.06,
      voiceHint: "female",
    },
    steps: [
      {
        clientMessage:
          "We're terminating an employee in a meeting right now. I need ALL their access cut immediately — this is sensitive.",
        clientMood: "panicked",
        kb: ["kb-verify-identity"],
        options: [
          {
            id: "verify-authorize",
            text: "\"Understood, treating this as urgent and confidential. Let me confirm this is an authorized HR offboarding and get the employee's exact account.\"",
            correct: true,
            reply: "Yes, authorized termination. The account is jdoe@helixlabs — go.",
            mood: "annoyed",
            csat: 8,
          },
          {
            id: "delete-account",
            text: "Immediately delete the user account entirely to be thorough.",
            correct: false,
            reply: "Wait — won't we lose their email and files we may need legally?",
            mood: "confused",
            csat: -12,
            coaching: "Disable, don't delete. Preserve data for legal/handover; deletion destroys evidence and files.",
          },
        ],
      },
      {
        clientMessage: "Account confirmed: jdoe. Cut it all, fast.",
        clientMood: "annoyed",
        kb: ["kb-mobile-mdm"],
        options: [
          {
            id: "disable-revoke",
            text: "Disable the account, revoke all sessions/tokens, reset the password, and remote-wipe corporate data from their devices.",
            correct: true,
            reply: "Sessions killed, device wiped, account disabled. That was exactly what we needed. Thank you.",
            mood: "calm",
            csat: 10,
          },
          {
            id: "password-only",
            text: "Just change the password and call it done.",
            correct: false,
            reply: "But they're still logged in on their laptop and phone right now!",
            mood: "panicked",
            csat: -14,
            coaching: "A password change alone doesn't kill active sessions. Revoke tokens and wipe devices too.",
          },
        ],
      },
      {
        clientMessage: "Access is cut. Anything else we should do?",
        clientMood: "calm",
        kb: ["kb-tone"],
        options: [
          {
            id: "handover",
            text: "Set an email auto-reply/forward to their manager, transfer file ownership, and document the offboarding timeline.",
            correct: true,
            reply: "Mailbox forwarded, files transferred, everything logged. Textbook offboarding — appreciate it.",
            mood: "friendly",
            csat: 9,
          },
          {
            id: "done",
            text: "\"That's everything, we're done here.\"",
            correct: false,
            reply: "What about their emails and shared files the team still needs?",
            mood: "confused",
            csat: -6,
            coaching: "Offboarding includes handover: forward mail and transfer ownership of their work.",
          },
        ],
      },
    ],
  },
  {
    id: "data-recovery",
    title: "VIP deleted the board deck",
    category: "Software",
    tier: "VIP",
    difficulty: 4,
    minLevel: 3,
    xp: 160,
    slaSeconds: 200,
    tags: ["data-recovery", "files", "backup"],
    summary: "A VP permanently deleted a critical presentation an hour before the board.",
    persona: {
      name: "Harold Vance",
      role: "VP of Strategy",
      company: "Meridian Bank",
      avatar: "🧓",
      pitch: 0.9,
      rate: 1.0,
      voiceHint: "male",
    },
    steps: [
      {
        clientMessage:
          "I deleted the board deck and emptied the recycle bin. The board meeting is in an hour. Please tell me it's recoverable!",
        clientMood: "panicked",
        kb: ["kb-tone"],
        options: [
          {
            id: "reassure-locate",
            text: "\"Don't panic — we have good options. Was the file on OneDrive/SharePoint or only on your local disk?\"",
            correct: true,
            reply: "It lived in our SharePoint 'Board' folder, synced to my laptop.",
            mood: "confused",
            csat: 9,
          },
          {
            id: "give-up",
            text: "\"If the recycle bin's empty, it's gone. Sorry.\"",
            correct: false,
            reply: "That's it?! You didn't even check for backups!",
            mood: "panicked",
            csat: -16,
            coaching: "Cloud storage has version history and a second-stage recycle bin. Never give up first.",
          },
        ],
      },
      {
        clientMessage: "It was on SharePoint. Does that help?",
        clientMood: "confused",
        options: [
          {
            id: "restore",
            text: "Restore it from the SharePoint site recycle bin / version history and confirm he can open the latest version.",
            correct: true,
            reply: "IT'S BACK — and it's the latest version! You just saved my board meeting.",
            mood: "friendly",
            csat: 10,
          },
          {
            id: "recreate",
            text: "Tell him to quickly rebuild the deck from scratch.",
            correct: false,
            reply: "Rebuild 40 slides in an hour? There has to be a recovery option!",
            mood: "panicked",
            csat: -12,
            coaching: "Use SharePoint's recycle bin and version history before asking anyone to recreate work.",
          },
        ],
      },
      {
        clientMessage: "Recovered! How do I keep this from happening again?",
        clientMood: "friendly",
        options: [
          {
            id: "educate",
            text: "Show him version history, confirm sync/backup is on, and note the recovery in the ticket.",
            correct: true,
            reply: "Version history is a revelation. I feel much safer now — thank you for staying calm.",
            mood: "friendly",
            csat: 8,
          },
          {
            id: "nothing2",
            text: "\"Just be more careful next time.\"",
            correct: false,
            reply: "A little tip on preventing it would've gone a long way.",
            mood: "annoyed",
            csat: -5,
            coaching: "Turn incidents into teaching moments — show them version history and backups.",
          },
        ],
      },
    ],
  },
];

export const scenarioById = (id: string) => SCENARIOS.find((s) => s.id === id);
